---
project:
  name: "grails-recaptcha"
  title: "Grails ReCaptcha Plugin"
  description: "Adds Google ReCaptcha support to Grails applications through a tag\
    \ library for rendering the captcha widget and a service for verifying the user's\
    \ response."
  org: "Grails Plugins Collective"
github:
  org: "gpc"
  project: "grails-recaptcha"
license:
  name: "Apache-2.0"
contributors:
  iamthechad: "Chad Johnston"
  sbglasius: "Søren Berg Glasius"
  bkoehm: "Brian Koehmstedt"
  vishnu-aggarwal-ttn: "Vishnu Aggarwal"
versions:
  current: "8.0.0-RC1"
  previous:
  - "8.0.0-RC1"
  ignore:
  - "8.0.x"
  - "snapshot"
